//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kimi.Resources.Commands.pt-BR", typeof(Commands_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aniversário!!!.
        /// </summary>
        internal static string birthday_description {
            get {
                return ResourceManager.GetString("birthday.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aniversario.
        /// </summary>
        internal static string birthday_name {
            get {
                return ResourceManager.GetString("birthday.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a data do seu aniversário do banco de dados.
        /// </summary>
        internal static string birthday_remove_description {
            get {
                return ResourceManager.GetString("birthday.remove.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remover.
        /// </summary>
        internal static string birthday_remove_name {
            get {
                return ResourceManager.GetString("birthday.remove.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dia do seu aniversário.
        /// </summary>
        internal static string birthday_set_day_description {
            get {
                return ResourceManager.GetString("birthday.set.day.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dia.
        /// </summary>
        internal static string birthday_set_day_name {
            get {
                return ResourceManager.GetString("birthday.set.day.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleciona a data do seu aniversário para você ganhar um cargo especial no dia.
        /// </summary>
        internal static string birthday_set_description {
            get {
                return ResourceManager.GetString("birthday.set.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        internal static string birthday_set_month_april_name {
            get {
                return ResourceManager.GetString("birthday.set.month.april.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        internal static string birthday_set_month_august_name {
            get {
                return ResourceManager.GetString("birthday.set.month.august.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezembro.
        /// </summary>
        internal static string birthday_set_month_december_name {
            get {
                return ResourceManager.GetString("birthday.set.month.december.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mês do seu aniversário.
        /// </summary>
        internal static string birthday_set_month_description {
            get {
                return ResourceManager.GetString("birthday.set.month.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fevereiro.
        /// </summary>
        internal static string birthday_set_month_february_name {
            get {
                return ResourceManager.GetString("birthday.set.month.february.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janeiro.
        /// </summary>
        internal static string birthday_set_month_january_name {
            get {
                return ResourceManager.GetString("birthday.set.month.january.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julho.
        /// </summary>
        internal static string birthday_set_month_july_name {
            get {
                return ResourceManager.GetString("birthday.set.month.july.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junho.
        /// </summary>
        internal static string birthday_set_month_june_name {
            get {
                return ResourceManager.GetString("birthday.set.month.june.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Março.
        /// </summary>
        internal static string birthday_set_month_march_name {
            get {
                return ResourceManager.GetString("birthday.set.month.march.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maio.
        /// </summary>
        internal static string birthday_set_month_may_name {
            get {
                return ResourceManager.GetString("birthday.set.month.may.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mes.
        /// </summary>
        internal static string birthday_set_month_name {
            get {
                return ResourceManager.GetString("birthday.set.month.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembro.
        /// </summary>
        internal static string birthday_set_month_november_name {
            get {
                return ResourceManager.GetString("birthday.set.month.november.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outubro.
        /// </summary>
        internal static string birthday_set_month_october_name {
            get {
                return ResourceManager.GetString("birthday.set.month.october.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setembro.
        /// </summary>
        internal static string birthday_set_month_september_name {
            get {
                return ResourceManager.GetString("birthday.set.month.september.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adicionar.
        /// </summary>
        internal static string birthday_set_name {
            get {
                return ResourceManager.GetString("birthday.set.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista o top 10 membros por pontuação.
        /// </summary>
        internal static string ranking_top_description {
            get {
                return ResourceManager.GetString("ranking.top.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resposta somente será exibida para você.
        /// </summary>
        internal static string ranking_top_ephemeral_description {
            get {
                return ResourceManager.GetString("ranking.top.ephemeral.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleciona qual ordem deve mostrar (pontos ou mensagens).
        /// </summary>
        internal static string ranking_top_order_by_description {
            get {
                return ResourceManager.GetString("ranking.top.order-by.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de mensagens.
        /// </summary>
        internal static string ranking_top_order_by_message_count_name {
            get {
                return ResourceManager.GetString("ranking.top.order-by.message-count.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ordem.
        /// </summary>
        internal static string ranking_top_order_by_name {
            get {
                return ResourceManager.GetString("ranking.top.order-by.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação.
        /// </summary>
        internal static string ranking_top_order_by_score_name {
            get {
                return ResourceManager.GetString("ranking.top.order-by.score.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleciona a página - ex. página 3 para a 21ª à 30ª posição.
        /// </summary>
        internal static string ranking_top_page_description {
            get {
                return ResourceManager.GetString("ranking.top.page.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagina.
        /// </summary>
        internal static string ranking_top_page_name {
            get {
                return ResourceManager.GetString("ranking.top.page.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sempre.
        /// </summary>
        internal static string ranking_top_period_all_time_name {
            get {
                return ResourceManager.GetString("ranking.top.period.all-time.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia.
        /// </summary>
        internal static string ranking_top_period_daily_name {
            get {
                return ResourceManager.GetString("ranking.top.period.daily.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data final. Se nenhuma data for providenciada, o dia de hoje será considerado.
        /// </summary>
        internal static string ranking_top_period_end_date_description {
            get {
                return ResourceManager.GetString("ranking.top-period.end-date.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data-final.
        /// </summary>
        internal static string ranking_top_period_end_date_name {
            get {
                return ResourceManager.GetString("ranking.top-period.end-date.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resposta somente será exibida para você.
        /// </summary>
        internal static string ranking_top_period_ephemeral_description {
            get {
                return ResourceManager.GetString("ranking.top-period.ephemeral.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês.
        /// </summary>
        internal static string ranking_top_period_monthly_name {
            get {
                return ResourceManager.GetString("ranking.top.period.monthly.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleciona qual ordem deve mostrar (pontos ou mensagens).
        /// </summary>
        internal static string ranking_top_period_order_by_description {
            get {
                return ResourceManager.GetString("ranking.top-period.order-by.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de mensagens.
        /// </summary>
        internal static string ranking_top_period_order_by_message_count_name {
            get {
                return ResourceManager.GetString("ranking.top-period.order-by.message-count.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ordem.
        /// </summary>
        internal static string ranking_top_period_order_by_name {
            get {
                return ResourceManager.GetString("ranking.top-period.order-by.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação.
        /// </summary>
        internal static string ranking_top_period_order_by_score_name {
            get {
                return ResourceManager.GetString("ranking.top-period.order-by.score.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleciona a página - ex. página 3 para a 21ª à 30ª posição.
        /// </summary>
        internal static string ranking_top_period_page_description {
            get {
                return ResourceManager.GetString("ranking.top-period.page.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagina.
        /// </summary>
        internal static string ranking_top_period_page_name {
            get {
                return ResourceManager.GetString("ranking.top-period.page.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data inicial. Formatação: dd/mm/yyyy OU yyyy/mm/dd.
        /// </summary>
        internal static string ranking_top_period_start_date_description {
            get {
                return ResourceManager.GetString("ranking.top-period.start-date.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data-inicial.
        /// </summary>
        internal static string ranking_top_period_start_date_name {
            get {
                return ResourceManager.GetString("ranking.top-period.start-date.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana.
        /// </summary>
        internal static string ranking_top_period_weekly_name {
            get {
                return ResourceManager.GetString("ranking.top.period.weekly.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        internal static string ranking_top_period_yearly_name {
            get {
                return ResourceManager.GetString("ranking.top.period.yearly.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano até agora.
        /// </summary>
        internal static string ranking_top_period_ytd_name {
            get {
                return ResourceManager.GetString("ranking.top.period.ytd.name", resourceCulture);
            }
        }
    }
}
